/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author DinerVJ
 */
public class VistaUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaUsuario
     */
    public VistaUsuario() {
        initComponents();
        setSize(730,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtUsername = new javax.swing.JTextField();
        jtxtPassword = new javax.swing.JTextField();
        jcbProfile = new javax.swing.JComboBox<>();
        jcbActive = new javax.swing.JComboBox<>();
        jbtnRegistrarUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblUser = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 0, 0));
        setOpaque(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtUsername.setBackground(new java.awt.Color(204, 102, 0));
        jtxtUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtxtUsername.setForeground(new java.awt.Color(0, 0, 0));
        jtxtUsername.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "USUARIO:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jtxtUsername.setOpaque(true);
        getContentPane().add(jtxtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 200, 50));

        jtxtPassword.setBackground(new java.awt.Color(204, 102, 0));
        jtxtPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtxtPassword.setForeground(new java.awt.Color(0, 0, 0));
        jtxtPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTRASEÑA:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jtxtPassword.setOpaque(true);
        getContentPane().add(jtxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 200, 60));

        jcbProfile.setBackground(new java.awt.Color(204, 102, 0));
        jcbProfile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcbProfile.setForeground(new java.awt.Color(0, 0, 0));
        jcbProfile.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRIVILEGIO:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jcbProfile.setOpaque(true);
        jcbProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbProfileActionPerformed(evt);
            }
        });
        getContentPane().add(jcbProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 200, 60));

        jcbActive.setBackground(new java.awt.Color(204, 102, 0));
        jcbActive.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcbActive.setForeground(new java.awt.Color(0, 0, 0));
        jcbActive.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ESTADO:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jcbActive.setOpaque(true);
        jcbActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbActiveActionPerformed(evt);
            }
        });
        getContentPane().add(jcbActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 200, 60));

        jbtnRegistrarUser.setBackground(new java.awt.Color(0, 0, 153));
        jbtnRegistrarUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnRegistrarUser.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRegistrarUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/disquete.png"))); // NOI18N
        jbtnRegistrarUser.setText("REGISTRAR");
        getContentPane().add(jbtnRegistrarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 200, 50));

        jtblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtblUser);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 650, 200));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("0 - INACTIVO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("1 - ACTIVO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbProfileActionPerformed

    private void jcbActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbActiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbActiveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtnRegistrarUser;
    public javax.swing.JComboBox<String> jcbActive;
    public javax.swing.JComboBox<String> jcbProfile;
    public javax.swing.JTable jtblUser;
    public javax.swing.JTextField jtxtPassword;
    public javax.swing.JTextField jtxtUsername;
    // End of variables declaration//GEN-END:variables
}
